### ISSUE TITLE
procure new amd64-based node

### ISSUE THREAD

**Issue by billimek** [billimek/homelab-infrastructure#13]
About to give on on trying to make raspberry pi work in this environment due to stability issues (see #12) and multi-arch challenges.

Looking at a SFF amd64 like another odroid-H2, amd ibox thing, deskmini, or something else.  Ideally it would be a 4 or 8 core 32GB box supporting an M2 nvme (for boot/OS/cluster stuff) and 2.5" SSD (for ceph OSD).  dual NICs is a plus but probably not necessary.

**Comment by runningman84** [comment]
I would suggest to look into the msi cubi n series. They consume only 4watt at idle and have a tdp of 6watt. I have three of them and they are great.

**Comment by billimek** [comment]
The pi4's have been very stable (~1 month of uptime now) - this is no longer a pressing issue.
