### ISSUE TITLE
proxmox hardware?

### ISSUE THREAD

**Issue by jp83** [billimek/homelab-infrastructure#3]
I didn't see it on your wiki diagram, just curious, what's the hardware for your proxmox hosts?  I keep re-thinking my infrastructure trying to balance between redundancy, storage, and power/heat (cost).

Also, are you running many other VMs on proxmox or mostly just the k8s nodes?  I've been using a single free ESXi host, and tried proxmox with the hope of terraforming it, but ran into lots of issues/lack of docs and abandoned.  If I can settle on storage and general understanding/stability, I keep thinking I might go all-in on bare metal k8s nodes (but that might still run into the same ceph problem I suppose).

**Comment by billimek** [comment]
closing via #5

**Comment by carpenike** [comment]
Been thinking about this the last few days and wanted to see where you were at on it.

The Odroid-H2s have two SATA ports on them. I’ve been stocking up on some 1TB Samsung Enterprise SSDs over the last few years and have 9 now. Thinking I could get 5x H2s whenever they become available and replace all my Proxmox nodes with rook-Ceph. Does that sound reasonable to you or do you have concerns with the performance you’ve seen with the Odroids? Any concerns with only 1GB networking and CEPH?
